### ISSUE TITLE
clarifying questions that emerged from basic tests in documentation 

### ISSUE THREAD

**Issue by matschil** [iampatbrown/thingy-pool#5]
Hey Pat,
had a fun time this morning doing some very basic testing on the thingy-pool!  
Love the documentation and that the package is pretty straight forward to use. Didn't have look into the code so far but played around with the functions the package offers. 

For me (never used an object-pool before) some questions emerged from the documentation: 
1. What exactly happens when a pool is stopped (it seems that all objects get destroyed?)
2. Can a stopped pool be started again with pool.start()? 

Currently, if the factory is inconsistent in itself, meaning that `factory.validate()` will always return `false` for an object created with `factory.create()` a pool with `shouldValidateOnDispatch = true` seems to infinitely try (but fails) to provide objects once `pool.acquire()` is called. 
(This might be intended as the user of the function should of course make sure the factory works properly)

Pasted the .js script I used to try out the code below (could have used jest to write proper tests though).

This is the first issue I created on an open source project, so im not sure whether this is the right place to provide personal messages. Feeling a bit like a grandma posting personal messages to the public feed of her grandchilds.  
Anyways, nice work man! Might have a closer look into the code later

```
const Pool = require('thingy-pool');
let index = 0
const factory = {
	create: () => {
		return { test: `test-${Math.random()}`}
	},
	destroy: (toDelete) => {
		// Pretend to delete -> mark object as collectible
		delete toDelete.test
	},
	// How often do you create and validate objects if the validate function does not validate the created objects of the pool?
	validate: (toValidate) => {
		index++;
		console.log(index)
		//return false
		return true;
	} 
}
const options = { minSize: 2, maxSize: 5, shouldValidateOnDispatch: true };

async function usePool(){
	// upon instanciation: Pool creates 2 objects from the factory (recheck)
	const pool = new Pool(factory, options);

	// first 5 acquired objects
	const acquiredObjects = [];
	for(let elem of [1,2,3,4,5]){
		console.log(`waiting for pool to return object ${elem}`)
		let acquiredObject = await pool.acquire({ timeoutInMs: 1000 })
		console.log(`${acquiredObject.test} was acquired successfully`)
		acquiredObjects.push(acquiredObject);

		// copy acquired object
		let copyOfAcquiredObject = Object.assign({}, acquiredObject)

		// test pool.has() with acquired object and with copy of acquired object
		let poolHas = pool.has(copyOfAcquiredObject);
		console.log(`pool.has() with copy of qcquired object returned: ${poolHas}`)
		poolHas = pool.has(acquiredObject);
		console.log(`pool.has() with acquired object returned: ${poolHas}`)

		// test pool.borrow() with acquired object and with copy of acquired object
		let poolBorrowed = pool.isBorrowed(copyOfAcquiredObject)
		console.log(`pool.isBorrowed() with copy of acquired object returned: ${poolBorrowed}`)
		poolBorrowed = pool.isBorrowed(acquiredObject)
		console.log(`pool.isBorrowed() with acquired object returned: ${poolBorrowed}`)

	}
	// 6th acquired object
	let threwError = false;
	try{
		acquiredObject = await pool.acquire({ timeoutInMs: 1000 })
	} catch(error){
		threwError = true; 
	}
	console.log(`threw error after quiring more objects than defined in option maxSize: ${threwError}`)

	// Releasing all objects: 
	for(let objectToRelease of acquiredObjects){
		await pool.release(objectToRelease)
	}

	// Release object that didnt exist
	threwError = false
	try{
		await pool.release({test: 'vito sucks balls'})
	}
	catch(error){
		threwError = true;
	}
	console.log(`threw error when releasing a non-existing object: ${threwError}`)
	
	// Try to stop pool and create new object
	await pool.stop()
	threwError = false; 
	try{
		await pool.acquire({ timeoutInMs: 1000 })
	}
	catch(error){
		threwError = true;
	}
	console.log(`threw error when aquiring new object after pool was stopped: ${threwError}`)

	// Start pool again -> What happens to objects once a pool is stopped?
	// Can pool get started again when it is stopped?
	console.log(pool.getInfo())
	await pool.start()
	console.log(pool.getInfo())
	acquiredObject = await pool.acquire({ timeoutInMs: 1000 })
	console.log(acquiredObject)
}

usePool()
```

**Comment by iampatbrown** [comment]
Hey Buddy :) Thanks heaps for checking it out. 

Lots of the functionality I've added based on other object pools. I originally needed something pretty simple and started building it before I knew what an object pool was. It gave me a good opportunity to learn and was lots of fun. Deciding how things worked was challenging because I wasn't sure how other people would use it. I debated with myself about the pros and cons of so many different things :P 

I'm not sure what people think about personal messages here, but I'm cool with it Grandma :)

I really appreciate the questions. I'll do my best to answer you questions and check out your code tonight. 
 
1. Yes the pool stops and destroys all objects. It does some other stuff as well which I've tried to describe in the code. See below
```js
  /**
   * Stops the pool and destroys all objects
   */
  async _stop() {
    // do we have to wait for any create promises as well?
    this._cancelNextIdleObjectCheck();
    // wait for outstanding requests to be fulfilled... could add an option to reject these requests ie. pool.forceStop()...
    const outstandingRequests = [...this._requests].map(request => toSafePromise(request.getPromise()));
    await Promise.all(outstandingRequests);
    // now that there are no more requests, destroy remaining available objects
    await this.clear();
    // wait for any objects to be returned
    const outstandingLoans = [...this._borrowed].map(pooledObject => pooledObject.getLoanPromise());
    await Promise.all(outstandingLoans);
    // wait for the returned objects to finish validating if shouldValidateOnReturn is enabled
    await Promise.all(this._validatePromises);
    // destroy remaining objects
    await this.clear();
    this._state = PoolStates.STOPPED;
    /**
     * Pool has stopped and all objects have been destroyed
     * @event Pool#poolDidStop
     */
    // should we attach anything to this event? and should we possibly emit events on the next loop?
    this.emit(PoolEvents.STOPPED);
  }
```
2. It can't be started again. I never really had a need to stop my pool. Not too sure if people would want to be able to restart it. If someone wanted to pause the pool we could probably do that a different way. Also right now the options can't be changed while the pool is running. I've set this up to be easy to change though if needed. 

As for factory.validate()... if it returned false all the time the pool would kind of just keep looping. Requests should time out though... at one point I was throwing an error if the object was invalid which could then be listened for by factoryValidateError but then I changed thinking there's a difference between an error from the factory and an object being invalid. Maybe we could add some extra events like 'objectFailedDispatch' and 'objectFailedReturn'. I considered having options that would check for things like this but thought it was best to leave the responsibility to the creator of the factory. Errors can be thrown but if the factory is returning false more often than it should maybe the factory could keep an internal count.

Let me know if that makes sense? 

It's possible I made this response too long...

**Comment by iampatbrown** [comment]
Awesome!

You picked up on something pretty important. If the factory always fails instantly the pool will stay in a the same event loop iteration which prevents the requests from timing out. I tried to keep the pool's pump cycle in the same loop as much as possible (pump is just a word I used to mean 'do whatever you need to to right now'). 
This could be fixed by adding `await new Promise(resolve => setImmediate(resolve))` to the _validateThenDispatchOrDestroy method like so.
```js
  async _validateThenDispatchOrDestroy(pooledObject) {
    pooledObject.setToValidating();
    this._beingValidatedForDispatch.add(pooledObject);
    const isValid = await this._factoryValidate(pooledObject.getObject());
    this._beingValidatedForDispatch.delete(pooledObject);
    if (isValid) {
      this._dispatch(pooledObject);
    } else {
      this._destroy(pooledObject);
      // await new Promise(resolve => setImmediate(resolve));
      this._pump()
    }
  }
```

Not sure what other implications this would have though. I'll do some testings :)

Thanks again man!

**Comment by iampatbrown** [comment]
Using the setImmediate fix for now
